### ISSUE TITLE
Issue with the booru commands

### ISSUE THREAD

**Issue by Justwinning** [Jintaku/Jintaku-Cogs-V3#22]
All the **booru cog commands** aren't working right now and are giving me errors when I try them, this is what it tells me when I tried the neko command,

```
[2020-02-20 17:22:19] [ERROR] red: Exception in command 'neko'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\discord\ext\commands\core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Red-DiscordBot\Red-DiscordBot\cogs\CogManager\cogs\booru\boorualias.py", line 21, in neko
    await self.generic_alias_booru(ctx, boards, tag)
  File "C:\Users\Administrator\AppData\Local\Red-DiscordBot\Red-DiscordBot\cogs\CogManager\cogs\booru\boorucore.py", line 121, in generic_alias_booru
    all_data = await asyncio.gather(*(getattr(self, f"fetch_{board}")(ctx, tag) for board in boards))
  File "C:\Users\Administrator\AppData\Local\Red-DiscordBot\Red-DiscordBot\cogs\Downloader\lib\aiocache\decorators.py", line 85, in wrapper
    return await self.decorator(f, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Red-DiscordBot\Red-DiscordBot\cogs\Downloader\lib\aiocache\decorators.py", line 98, in decorator
    result = await f(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Red-DiscordBot\Red-DiscordBot\cogs\CogManager\cogs\booru\boorucore.py", line 945, in fetch_dan
    return await self.fetch_from_booru(urlstr, "Danbooru")
  File "C:\Users\Administrator\AppData\Local\Red-DiscordBot\Red-DiscordBot\cogs\CogManager\cogs\booru\boorucore.py", line 905, in fetch_from_booru
    item["author"] = item["uploader_name"]
KeyError: 'uploader_name'
```
Im getting the same error for all the Booru cog commands, please look into this issue thanks.

**Comment by kennnyshiwa** [comment]
@Justwinning should be fixed now

**Comment by Justwinning** [comment]
Its working now, thanks!
