### ISSUE TITLE
Error in gamesearch

### ISSUE THREAD

**Issue by sverit** [Jintaku/Jintaku-Cogs-V3#32]
Hi,

the gamesearch cog isn't working for me right now. I get the following error:
> Error in command 'game'. Check your console or logs for details.

The console output is as follows:
```
[2020-08-14 16:51:39] [ERROR] red: Exception in command 'game'
Traceback (most recent call last):
  File "/home/redbot/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/redbot/.local/share/Red-DiscordBot/data/Bot/cogs/CogManager/cogs/gamesearch/gamesearch.py", line 85, in game
    embeds = await asyncio.gather(*(self.get_game_embed(headers, game_data) for game_data in games_data))
  File "/home/redbot/.local/share/Red-DiscordBot/data/Bot/cogs/CogManager/cogs/gamesearch/gamesearch.py", line 49, in get_game_embed
    embed = discord.Embed(title=game_data["name"], url=game_data["url"])
KeyError: 'name'

```

Thanks for your awesome work though :)

**Comment by lionirdeadman** [comment]
What command did you try?

**Comment by sverit** [comment]
Nothing special, happens regardless of the input:
![2020-08-14 19_45_45-Clipboard](https://user-images.githubusercontent.com/31847769/90277905-c3216e80-de66-11ea-8b87-3a8b3630a83e.png)

**Comment by lionirdeadman** [comment]
Hm, that does work here. Are you up to date and is your igdb key set properly?

**Comment by sverit** [comment]
Thank you, it was indeed the case that my IGBB API key was surprisingly no longer working. I created a new one and now everything works fine again. Thank you for your time :)
