### ISSUE TITLE
All the booru cog commands aren't working right now and are giving me errors when I try them, this is what it tells me when I tried the neko command

### ISSUE THREAD

**Issue by Thalamuszen** [Jintaku/Jintaku-Cogs-V3#37]
[2020-09-06 23:30:57] [ERROR] red: Exception in command 'neko'
Traceback (most recent call last):
  File "c:\users\thalamus\redenv\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Thalamus\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\Elune\cogs\CogManager\cogs\booru\boorualias.py", line 21, in neko
    await self.generic_alias_booru(ctx, boards, tag)
  File "C:\Users\Thalamus\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\Elune\cogs\CogManager\cogs\booru\boorucore.py", line 121, in generic_alias_booru
    all_data = await asyncio.gather(*(getattr(self, f"fetch_{board}")(ctx, tag) for board in boards))
  File "C:\Users\Thalamus\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\Elune\cogs\Downloader\lib\aiocache\decorators.py", line 85, in wrapper
    return await self.decorator(f, *args, **kwargs)
  File "C:\Users\Thalamus\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\Elune\cogs\Downloader\lib\aiocache\decorators.py", line 98, in decorator
    result = await f(*args, **kwargs)
  File "C:\Users\Thalamus\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\Elune\cogs\CogManager\cogs\booru\boorucore.py", line 941, in fetch_dan
    return await self.fetch_from_booru(urlstr, "Danbooru")
  File "C:\Users\Thalamus\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\Elune\cogs\CogManager\cogs\booru\boorucore.py", line 895, in fetch_from_booru
    item["post_link"] = "https://danbooru.donmai.us/posts/" + str(item["id"])
KeyError: 'id'

**Comment by lionirdeadman** [comment]
Can you do updates? I can't reproduce this.

**Comment by Thalamuszen** [comment]
Only installed the cog today. Probably something wrong my end if you can't reproduce.Will try updating it tomorrow.On 7 Sep 2020 01:49, Lionir <notifications@github.com> wrote:
Can you do updates? I can't reproduce this.

**Comment by lionirdeadman** [comment]
Hm, nah, if you installed today, it can't be updates. Can you give me the exact command you did?

**Comment by Thalamuszen** [comment]
The current prefix I am using is EL.So the command I ran for this specific error is ELnekoThough I will say that it does error for all commands except the Booru commands.The errors all look near identical in the console.On 7 Sep 2020 02:40, Lionir <notifications@github.com> wrote:
Hm, nah, if you installed today, it can't be updates. Can you give me the exact command you did?

**Comment by lionirdeadman** [comment]
Okay, I figured out how to reproduce. It seems to only crash in NSFW rooms. I'm guessing danbooru is giving me garbage again. Will see how to clean that up.
