### ISSUE TITLE
gamesearch : KeyError: 'cover'

### ISSUE THREAD

**Issue by mjdelro** [Jintaku/Jintaku-Cogs-V3#5]
Pulled this error when I tried to use the `gamesearch` cog using the command
`[p]game vesperia` to test functionality.

Looks like it's not able to parse the `cover` var

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/ubuntu/.local/share/Red-DiscordBot/cogs/CogManager/cogs/gamesearch/gamesearch.py", line 74, in game
    embeds = await asyncio.gather(*(self.get_game_embed(headers, game_data) for game_data in games_data))
  File "/home/ubuntu/.local/share/Red-DiscordBot/cogs/CogManager/cogs/gamesearch/gamesearch.py", line 31, in get_game_embed
    cover_query = f"fields url; where id = {game_data['cover']};".encode()
KeyError: 'cover'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/bot.py", line 912, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 643, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'cover'
```

**Comment by lionirdeadman** [comment]
Fixed with df6cc0f6ff4da8e824ee28ea82c087bbd809ead2
