### ISSUE TITLE
Booru Error in command 'booru'. Check your console or logs for details.

### ISSUE THREAD

**Issue by Ming-A** [Jintaku/Jintaku-Cogs-V3#54]
Im getting this in the log, i did [p]booru hentai and also tried [p]booru smile score but got the same error
```
,
The above exception was the direct cause of the following exception:,
,
Traceback (most recent call last):,
  File "/data/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped,
    ret = await coro(*args, **kwargs),
  File "/data/cogs/CogManager/cogs/booru/booru.py", line 54, in booru,
    await self.generic_booru(ctx, tag),
  File "/data/cogs/CogManager/cogs/booru/boorucore.py", line 77, in generic_booru,
    all_data = await asyncio.gather(*(getattr(self, f"fetch_{board}")(ctx, tag) for board in boards)),
  File "/data/cogs/Downloader/lib/aiocache/decorators.py", line 85, in wrapper,
    return await self.decorator(f, *args, **kwargs),
  File "/data/cogs/Downloader/lib/aiocache/decorators.py", line 98, in decorator,
    result = await f(*args, **kwargs),
  File "/data/cogs/CogManager/cogs/booru/boorucore.py", line 922, in fetch_gel,
    return await self.fetch_from_booru(urlstr, "Gelbooru"),
  File "/data/cogs/CogManager/cogs/booru/boorucore.py", line 865, in fetch_from_booru,
    async with self.session.get(urlstr, headers={'User-Agent': "Booru (https://github.com/Jintaku/Jintaku-Cogs-V3)"}) as resp:,
  File "/data/venv/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__,
    self._resp = await self._coro,
  File "/data/venv/lib/python3.8/site-packages/aiohttp/client.py", line 480, in _request,
    conn = await self._connector.connect(,
  File "/data/venv/lib/python3.8/site-packages/aiohttp/connector.py", line 523, in connect,
    proto = await self._create_connection(req, traces, timeout),
  File "/data/venv/lib/python3.8/site-packages/aiohttp/connector.py", line 858, in _create_connection,
    _, proto = await self._create_direct_connection(,
  File "/data/venv/lib/python3.8/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection,
    raise last_exc,
  File "/data/venv/lib/python3.8/site-packages/aiohttp/connector.py", line 980, in _create_direct_connection,
    transp, proto = await self._wrap_create_connection(,
  File "/data/venv/lib/python3.8/site-packages/aiohttp/connector.py", line 943, in _wrap_create_connection,
    raise client_error(req.connection_key, exc) from exc,
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gelbooru.com:443 ssl:default [Connection refused],
```

**Comment by ghost** [comment]
I can also confirm this

**Comment by Mrs-Feathers** [comment]
i can also confirm. this is the error i'm getting too.
