### ISSUE TITLE
osu error when you dont have stats.

### ISSUE THREAD

**Issue by ltzmax** [Jintaku/Jintaku-Cogs-V3#56]
So i setup the osu cog and it actually error out if user dont have any stats. but works if you have a level or two or more. but not without that.

```
Traceback (most recent call last):
  File "/home/aina/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/aina/redbot/cogs/CogManager/cogs/osu/osu.py", line 41, in osu
    embed.add_field(name="Accuracy", value=osu[0]["accuracy"][:6])
TypeError: 'NoneType' object is not subscriptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/aina/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "/home/aina/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 864, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/aina/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: 'NoneType' object is not subscriptable
```

**Comment by ltzmax** [comment]
oof... well since nothing has been updated for loooong time i guess... yep
